# Generated by Django 5.0.9 on 2024-10-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0003_remove_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_path',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='video_path',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
