# Generated by Django 5.0.9 on 2024-10-10 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0004_alter_artwork_image_path_alter_artwork_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='appln.user'),
        ),
    ]
