# Generated by Django 5.0.9 on 2024-10-12 03:14

import appln.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0005_artist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[appln.validators.ValidateEmailImpl]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='first_name',
            field=models.CharField(max_length=255, validators=[appln.validators.ValidateNameImpl]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='last_name',
            field=models.CharField(max_length=255, validators=[appln.validators.ValidateNameImpl]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[appln.validators.ValidatePhoneNumberImpl]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='username',
            field=models.CharField(max_length=255, unique=True, validators=[appln.validators.ValidateUserNameImpl]),
        ),
    ]
