# Generated by Django 5.0.9 on 2024-10-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0005_artist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
