# Generated by Django 5.0.9 on 2024-10-16 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0006_artistprofile_profile_photo'),
        ('appln', '0007_alter_artwork_description_alter_artwork_price_and_more'),
    ]

    operations = [
    ]
