# Generated by Django 5.0.9 on 2024-10-16 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0008_merge_20241015_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='social_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
