# Generated by Django 5.0.9 on 2024-10-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0009_alter_artistprofile_social_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='is_image',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_video',
        ),
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
