# Generated by Django 5.0.9 on 2024-10-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0010_remove_request_is_image_remove_request_is_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='artist_delivery_date',
            field=models.DateTimeField(null=True),
        ),
    ]
