# Generated by Django 5.0.9 on 2024-10-23 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0011_alter_order_artist_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='appln.request'),
        ),
    ]
