# Generated by Django 5.0.9 on 2024-10-23 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0012_order_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='appln.request'),
            preserve_default=False,
        ),
    ]
