# Generated by Django 5.0.9 on 2024-11-07 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0013_alter_order_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file_path',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
