# Generated by Django 5.0.9 on 2024-11-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appln', '0015_alter_upload_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='appln.request'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='appln.request'),
        ),
    ]
